### ISSUE TITLE
Gem awesome_print required

### ISSUE THREAD

**Issue by chrismitchell** [jakeonrails/annotate_gemfile#1]
I ran into an issue when trying to run annotate-gemfile. 

``` bash
± annotate-gemfile
/Users/chrismitchell/.rvm/gems/ruby-2.3.0@foxyloxy/gems/annotate_gemfile-0.1.1/lib/annotate_gemfile/annotator.rb:4:in `require': cannot load such file -- awesome_print (LoadError)
    from /Users/chrismitchell/.rvm/gems/ruby-2.3.0@foxyloxy/gems/annotate_gemfile-0.1.1/lib/annotate_gemfile/annotator.rb:4:in `<top (required)>'
    from /Users/chrismitchell/.rvm/gems/ruby-2.3.0@foxyloxy/gems/annotate_gemfile-0.1.1/lib/annotate_gemfile.rb:2:in `require'
    from /Users/chrismitchell/.rvm/gems/ruby-2.3.0@foxyloxy/gems/annotate_gemfile-0.1.1/lib/annotate_gemfile.rb:2:in `<top (required)>'
    from /Users/chrismitchell/.rvm/gems/ruby-2.3.0@foxyloxy/gems/annotate_gemfile-0.1.1/bin/annotate-gemfile:2:in `require'
    from /Users/chrismitchell/.rvm/gems/ruby-2.3.0@foxyloxy/gems/annotate_gemfile-0.1.1/bin/annotate-gemfile:2:in `<top (required)>'
    from /Users/chrismitchell/.rvm/gems/ruby-2.3.0@foxyloxy/bin/annotate-gemfile:23:in `load'
    from /Users/chrismitchell/.rvm/gems/ruby-2.3.0@foxyloxy/bin/annotate-gemfile:23:in `<main>'
    from /Users/chrismitchell/.rvm/gems/ruby-2.3.0@foxyloxy/bin/ruby_executable_hooks:15:in `eval'
    from /Users/chrismitchell/.rvm/gems/ruby-2.3.0@foxyloxy/bin/ruby_executable_hooks:15:in `<main>'
```

I added `awesome_print` to my Gemfile and it worked. 

Thanks this is a nice little addition that I'll add to all my projects

**Comment by jakeonrails** [comment]
Oh thanks! I'll fix this and update! Glad you like it :)

**Comment by jakeonrails** [comment]
Check it out, version 0.1.2 is now available, and I've tested it in a secluded gemset to ensure it doesn't have the problem anymore! :)

**Comment by chrismitchell** [comment]
Worked for me. Closing out issue
